add 14 longest common prefix
kobakobashu/leetcode pull request #10
Opened 2021-04-08 13:26 UTC by kobakobashu

20m
Please check my code

2021-04-08 13:31 UTC, kobakobashu commented
また違うファイル入ってしまいました。。。直します。。github難しい。。。

2021-04-09 04:23 UTC, ryuji0123 requested changes
```py
class Solution:
    def longestCommonPrefix(self, strs: List[str]) -> str:
        M = len(strs)
        if M == 0:
            return ''
            
        N = min(len(s) for s in strs)
        for i in range(N):
            if any(strs[j][i] != strs[0][i] for j in range(M)):
                return strs[0][: i]
                    
        return strs[0][: N]
```

2021-04-09 04:23 UTC, ryuji0123 commented on 14.longest-common-prefix.py
> +            if flag == 1:
if flag is 0, you can return ans here

2021-04-09 04:23 UTC, ryuji0123 commented on 14.longest-common-prefix.py
> +        flag = 1
avoid using flag which isn't clear.

2021-04-09 09:05 UTC, kobakobashu commented
fixed my code. Please check it.

2021-04-10 06:28 UTC, ryuji0123 requested changes

2021-04-10 06:28 UTC, ryuji0123 commented on 14.longest-common-prefix.py
> +        if len(strs) == 0:
```py
if not str:
```

2021-04-10 06:28 UTC, ryuji0123 commented on 14.longest-common-prefix.py
> +        return (ans)
```py
return ans
```

2021-04-10 06:28 UTC, ryuji0123 commented on 14.longest-common-prefix.py
> +                    return (ans)
```py
return ans
```

2021-04-10 09:38 UTC, kobakobashu commented
fixed my code. Please check it.

2021-04-10 11:55 UTC, ryuji0123 approved these changes
LGTM

2021-04-11 05:46 UTC, merged