add 21 merge-two-sorted-lists
kobakobashu/leetcode pull request #14
Opened 2021-04-10 11:04 UTC by kobakobashu

30m

2021-04-10 11:05 UTC, kobakobashu commented
forget writing time and space complexity.
please wait

2021-04-10 11:17 UTC, kobakobashu commented
Please check my code

2021-04-10 11:54 UTC, ryuji0123 requested changes
common names for this kind of problems are:
```py
head, cur_node, prev_node, next_node, tail
```

2021-04-10 11:54 UTC, ryuji0123 commented on 21.merge-two-sorted-lists.py
> +        output = ListNode(0)
```py
head = ListNode(0)
```

2021-04-10 11:54 UTC, ryuji0123 commented on 21.merge-two-sorted-lists.py
> +        output = ListNode(0)
```py
head = ListNode(0)
```

2021-04-10 11:54 UTC, ryuji0123 commented on 21.merge-two-sorted-lists.py
> +        output_add = output
```py
cur_node = head
```

2021-04-10 11:54 UTC, ryuji0123 commented on 21.merge-two-sorted-lists.py
> +        if not l1:
```py
cur_node.next = l1 if not l2 else l2
```

2021-04-11 08:38 UTC, kobakobashu commented
I fixed code.  Please check it

2021-04-11 09:07 UTC, ryuji0123 approved these changes
LGTM, but using head variable with dummy value is a little bit confusing. My answer is:

```py
# Definition for singly-linked list.
# class ListNode:
#     def __init__(self, val=0, next=None):
#         self.val = val
#         self.next = next
class Solution:
    def mergeTwoLists(self, l1: ListNode, l2: ListNode) -> ListNode:
        if not l1:
            return l2
        if not l2:
            return l1
        
        if l1.val <= l2.val:
            head = ListNode(l1.val)
            l1 = l1.next
        else:
            head = ListNode(l2.val)
            l2 = l2.next
        cur_node = head
        
        while l1 and l2:
            if l1.val <= l2.val:
                cur_node.next = ListNode(l1.val)
                l1 = l1.next
            else:
                cur_node.next = ListNode(l2.val)
                l2 = l2.next
            cur_node = cur_node.next
        
        cur_node.next = l1 if not l2 else l2
        
        return head
```

2021-04-12 00:12 UTC, merged