add 26 remove-duplicates-from-sorted-array
kobakobashu/leetcode pull request #16
Opened 2021-04-11 09:52 UTC by kobakobashu

20m

2021-04-11 09:53 UTC, kobakobashu commented
Please check my code

2021-04-11 10:32 UTC, ryuji0123 requested changes

2021-04-11 10:32 UTC, ryuji0123 commented on 26.remove-duplicates-from-sorted-array.py
> +        return i+1
return i + 1

2021-04-11 10:32 UTC, ryuji0123 commented on 26.remove-duplicates-from-sorted-array.py
> +        i = 0
i, j are unclear

2021-04-13 11:45 UTC, kobakobashu commented
Please check my code

2021-04-14 10:51 UTC, ryuji0123 approved these changes
LGTM

2021-04-14 11:14 UTC, merged