add 27 remove-element
kobakobashu/leetcode pull request #18
Opened 2021-04-12 00:50 UTC by kobakobashu

15m
Please check my code

2021-04-12 03:38 UTC, ryuji0123 requested changes

2021-04-12 03:38 UTC, ryuji0123 commented on 27.remove-element.py
> +        if len(nums) == 0:
See Google style 2.14.4 Decision. Maybe I said this before

```py
if not nums:
```

2021-04-13 11:49 UTC, kobakobashu commented
I fixed it.  Please check my code

2021-04-14 10:50 UTC, ryuji0123 approved these changes
LGTM

2021-04-14 11:14 UTC, merged