finish
kobakobashu/leetcode pull request #2
Opened 2021-04-04 03:05 UTC by kobakobashu

time : 10m

2021-04-04 03:31 UTC, ryuji0123 requested changes
- write time & space complexity
- for readability, change PR's title to two-sum
- use dict to reduce time complexity
- in this case, you don't have to check whether input is invalid, but sometimes you should

my answer is like:
```py
class Solution(object):
    def twoSum(self, nums, target):
        """
        :type nums: List[int]
        :type target: int
        :rtype: List[int]
        """
        if nums is None or target is None:
            return None
        ref = {}
        for idx, n in enumerate(nums):
            if target - n in ref:
                return [idx, ref[target - n]]
            ref[n] = idx
```

2021-04-04 13:06 UTC, ryuji0123 requested changes
Very close. From next time, if you can, write your own new answer after understanding key points.

2021-04-04 13:06 UTC, ryuji0123 commented on 1.two-sum.py
> +        space: O(n**2)
O(1)

2021-04-04 13:27 UTC, kobakobashu commented on 1.two-sum.py
> +        space: O(n**2)
for文は、繰り返す過程でメモリを書き換えるため、space complexityは n に依存しないという認識で ok ですか？

2021-04-04 13:27 UTC, ryuji0123 commented on 1.two-sum.py
> +        space: O(n**2)
その通り。

2021-04-04 13:29 UTC, ryuji0123 commented on 1.two-sum.py
> +        space: O(n**2)
space complexityは新たに確保したメモリの消費量として考えてください。この場合はnumが既に与えられており、関数内で割り当てた変数は全て O(1) しか消費してないです。

2021-04-04 13:30 UTC, kobakobashu commented on 1.two-sum.py
> +        space: O(n**2)
なるほど。ありがとうございます！！

2021-04-08 10:16 UTC, ryuji0123 commented
こちらそろそろ済ませましょう

2021-04-08 10:18 UTC, ryuji0123 approved these changes
LGTM (commit したら reviewer に指定して下さい)

2021-04-08 10:19 UTC, ryuji0123 commented
merge する前に main に rebase をかけて、 再度 push して下さい

2021-04-09 04:48 UTC, kobakobashu commented
承知しました。返信が遅れてしまい、申し訳ございません。

2021-04-09 06:59 UTC, kobakobashu commented
初 conflict 解消！！！！！！
merge します

2021-04-09 08:32 UTC, merged