add 28 implement-str-str
kobakobashu/leetcode pull request #20
Opened 2021-04-13 12:38 UTC by kobakobashu

10m

2021-04-13 12:39 UTC, kobakobashu commented
Please check my code

2021-04-14 10:48 UTC, ryuji0123 requested changes

2021-04-14 10:48 UTC, ryuji0123 commented on 28.implement-str-str.py
> +            haystack_part = haystack[i:i+len_needle]
haystack_part = haystack[i: i + len_needle]

2021-04-14 10:48 UTC, ryuji0123 commented on 28.implement-str-str.py
> +        len_haystack = len(haystack)
Are these variables necessary? Seems the length of them doesn't change.

2021-04-14 10:48 UTC, ryuji0123 commented on 28.implement-str-str.py
> +            haystack_part = haystack[i:i+len_needle]
O(len_needle)

2021-04-14 10:48 UTC, ryuji0123 commented on 28.implement-str-str.py
> +            if  haystack_part == needle:
O(max(len_needle, len_haystack_part))

2021-04-14 10:48 UTC, ryuji0123 commented on 28.implement-str-str.py
> +        time: O(len(haystack))
Is this right?

2021-04-15 08:51 UTC, kobakobashu commented on 28.implement-str-str.py
> +            if  haystack_part == needle:
time complexity が O(max(len_needle, len_haystack_part)) ということでしょうか。
for 文で最悪の場合、len(haystack) 回繰り返す必要があると考えたため、O(len(haystack)) と考えました。
よろしければ理由を教えて頂きたいです。

2021-04-15 09:07 UTC, ryuji0123 commented on 28.implement-str-str.py
> +            if  haystack_part == needle:
https://stackoverflow.com/questions/11313950/what-is-the-order-of-complexity-of-comparing-two-python-lists#:~:text=The%20complexity%20of%20comparing%20two,the%20lists%20have%20different%20lengths.&text=This%20very%20much%20depends%20on,of%20the%20word%20'comparison'.

2021-04-15 09:08 UTC, ryuji0123 commented on 28.implement-str-str.py
> +            if  haystack_part == needle:
max は正確な記載じゃないですね

2021-04-18 11:45 UTC, kobakobashu commented
I fixed my code.  Please check my code.

2021-04-21 13:09 UTC, ryuji0123 requested changes

2021-04-21 13:09 UTC, ryuji0123 commented on 28.implement-str-str.py
> +        O(len(needle))  if len(haystack) == len(needle)
You forget for loop
O(len(haystack) * len(needle)) if len(haystack) == len(needle)
O(len(haystack)) else

2021-04-23 14:34 UTC, kobakobashu commented
I fixed my code.  Please check it

2021-04-27 14:56 UTC, ryuji0123 approved these changes
LGTM

2021-04-28 01:46 UTC, merged