add 35 search-insert-position
kobakobashu/leetcode pull request #22
Opened 2021-04-14 07:11 UTC by kobakobashu

time: 5 m

2021-04-14 07:11 UTC, kobakobashu commented
Please check my code.

2021-04-14 10:44 UTC, ryuji0123 requested changes

2021-04-14 10:44 UTC, ryuji0123 commented on 35.search-insert-position.py
> +            #print(index)
delete this

2021-04-15 07:55 UTC, kobakobashu commented
I fixed my code.  Please check it.

2021-04-15 09:09 UTC, ryuji0123 approved these changes
LGTM

2021-04-16 10:19 UTC, merged