add 58 length-of-last-word
kobakobashu/leetcode pull request #26
Opened 2021-04-16 10:54 UTC by kobakobashu

time : 15m

2021-04-16 10:58 UTC, ryuji0123 requested changes

2021-04-16 10:58 UTC, ryuji0123 commented on 58.length-of-last-word.py
> +        l = s.split()
'l' is unclear

2021-04-16 10:58 UTC, ryuji0123 commented on 58.length-of-last-word.py
> +        if not l:
return len(l[-1]) if l else 0

2021-04-16 11:09 UTC, kobakobashu commented
I fixed my code.  Please check it.

2021-04-17 14:07 UTC, ryuji0123 approved these changes
LGTM

2021-04-18 10:19 UTC, merged