add 66 plus-one
kobakobashu/leetcode pull request #28
Opened 2021-04-16 13:14 UTC by kobakobashu

time : 20m

2021-04-16 13:15 UTC, kobakobashu commented
Please check my code.

2021-04-17 14:07 UTC, ryuji0123 requested changes
You can write simply

```py
class Solution:
    def plusOne(self, digits: List[int]) -> List[int]:
        return list(str(int(''.join([str(d) for d in digits])) + 1))
```

2021-04-17 14:07 UTC, ryuji0123 commented on 66.plus-one.py
> +            number_str += str(digit)
use list to avoid str concatination.

2021-04-18 11:05 UTC, kobakobashu commented
I fixed my code.  Please check it.

2021-04-21 13:10 UTC, ryuji0123 approved these changes
LGTM

2021-04-22 06:51 UTC, merged