add 67 add-binary
kobakobashu/leetcode pull request #30
Opened 2021-04-18 12:17 UTC by kobakobashu

time : 15m

2021-04-18 12:17 UTC, kobakobashu commented
Please check my code !

2021-04-19 03:32 UTC, ryuji0123 requested changes

2021-04-19 03:32 UTC, ryuji0123 commented on 67.add-binary.py
> +        output_10 = int(a,2) + int(b,2)
output_10 is ambiguous. Also, you don't have to initialize this variable.

```py
return bin(int(a,2) + int(b,2)).replace('0b', '')
```

2021-04-19 03:32 UTC, ryuji0123 commented on 67.add-binary.py
> +        time: O(1)
time complexity of int(str_1) is O(len(str_1))

2021-04-19 04:34 UTC, kobakobashu commented
I fixed my code!  Please check it!

2021-04-21 13:11 UTC, ryuji0123 approved these changes
LGTM

2021-04-22 06:51 UTC, merged