add 69 sqrt-x
kobakobashu/leetcode pull request #32
Opened 2021-04-19 05:18 UTC by kobakobashu

time : 5m

2021-04-19 05:19 UTC, kobakobashu commented
Please check my code.

2021-04-21 13:07 UTC, ryuji0123 requested changes

2021-04-21 13:07 UTC, ryuji0123 commented on 69.sqrt-x.py
> +        time: O(len(x))
why do you this O(len(x))? Show your reference.

2021-04-23 14:44 UTC, kobakobashu commented on 69.sqrt-x.py
> +        time: O(len(x))
add 67 での
time complexity of int(str_1) is O(len(str_1))
こちらのアドバイスとごちゃ混ぜになっていました。勘違いです。直します。

2021-04-23 14:47 UTC, kobakobashu commented
I fixed my code.  Please check it.

2021-04-27 14:55 UTC, ryuji0123 approved these changes
LGTM

2021-04-28 01:46 UTC, merged