climbing-stairs
kobakobashu/leetcode pull request #34
Opened 2021-04-20 08:19 UTC by kobakobashu

time : 15m

2021-04-20 08:20 UTC, kobakobashu commented
Please check my code.

2021-04-21 13:05 UTC, ryuji0123 requested changes

2021-04-21 13:05 UTC, ryuji0123 commented on 70.climbing-stairs.py
> +        step = [0]*(n+2)
step = [i if i <= 2 else 0 for i in range(n + 2)]

2021-04-21 13:05 UTC, ryuji0123 commented on 70.climbing-stairs.py
> +            for step_num in range(3,n+1):
for num_step in range(3,n+1):

2021-04-23 15:06 UTC, kobakobashu commented
I fixed my code.  Please check it.

2021-04-27 14:57 UTC, ryuji0123 approved these changes
LGTM

2021-04-28 01:46 UTC, merged