add 88 merge-sorted-array
kobakobashu/leetcode pull request #38
Opened 2021-04-22 14:09 UTC by kobakobashu

time : 20m

2021-04-22 14:09 UTC, kobakobashu commented
Please check my code.

2021-04-22 14:38 UTC, ryuji0123 requested changes
```py
class Solution:
    def merge(self, nums1: List[int], m: int, nums2: List[int], n: int) -> None:
        """
        Do not return anything, modify nums1 in-place instead.
        """
        for i, n in enumerate(sorted(nums1[: m] + nums2)):
            nums1[i] = n
```

2021-04-22 14:38 UTC, ryuji0123 commented on 88.merge-sorted-array.py
> +        del nums1[m:]
It seems to be weird to delete elements to modify elements in-place

2021-04-29 06:50 UTC, kobakobashu commented
I fixed my code.  Please check it.

2021-04-29 14:59 UTC, ryuji0123 approved these changes

2021-05-01 15:36 UTC, merged