add 101 symmetric-tree
kobakobashu/leetcode pull request #42
Opened 2021-04-24 15:31 UTC by kobakobashu

time : 50m

2021-04-24 15:32 UTC, kobakobashu commented
Please check my code.

2021-04-27 14:54 UTC, ryuji0123 requested changes
Good algorithm

2021-04-27 14:54 UTC, ryuji0123 commented on 101.symmetric-tree.py
> +        else:
You don't need to write else. Just return

2021-04-29 06:56 UTC, kobakobashu commented
I fixed my code.  Please check it.

2021-04-29 14:58 UTC, ryuji0123 requested changes

2021-04-29 14:58 UTC, ryuji0123 commented on 101.symmetric-tree.py
> +    def isMirror(self, left, right):
insert a line before function definition.

2021-05-01 15:42 UTC, kobakobashu commented
I fixed my code.  Please check my code.

2021-05-02 11:31 UTC, ryuji0123 requested changes

2021-05-02 11:31 UTC, ryuji0123 commented on 101.symmetric-tree.py
> +    def isMirror(self, left, right):
Check function name's character in PEP8. Unfortunately, function names in Leetcode break it, so you cannot use the same name style without checking coding style guides.

2021-05-04 01:28 UTC, kobakobashu commented
I rename function name.  Please check it.

2021-05-04 13:30 UTC, ryuji0123 requested changes

2021-05-04 13:30 UTC, ryuji0123 commented on 101.symmetric-tree.py
> +        else:
remove else or write like this:

```py
return True if not root else self.check_mirror(root.left, root.right)
```

2021-05-06 05:11 UTC, kobakobashu commented
I removed else and wrote type hints and docstring.  Please check it.

2021-12-13 06:43 UTC, merged