add 108 convert-sorted-array-to-binary-search-tree
kobakobashu/leetcode pull request #46
Opened 2021-04-26 16:41 UTC by kobakobashu

time : 25m

2021-04-26 16:41 UTC, kobakobashu commented
Please check my code.

2021-04-27 14:38 UTC, ryuji0123 requested changes

2021-04-27 14:38 UTC, ryuji0123 commented on 108.convert-sorted-array-to-binary-search-tree.py
> +        node = TreeNode(nums[half], None, None)
You don't need to specify values that are the same ones with default values.
```py
node = TreeNode(nums[half])
```

2021-04-29 07:00 UTC, kobakobashu commented
I fixed my code.  Please check it.

2021-04-29 14:52 UTC, ryuji0123 requested changes

2021-04-29 14:52 UTC, ryuji0123 commented on 108.convert-sorted-array-to-binary-search-tree.py
> +            return None
insert a line after return statement.

2021-05-01 15:46 UTC, kobakobashu commented
I fixed my code.  Please check it.

2021-05-02 11:33 UTC, ryuji0123 requested changes
Check "Readable code"

2021-05-02 11:33 UTC, ryuji0123 commented on 108.convert-sorted-array-to-binary-search-tree.py
> +        node.right = self.sortedArrayToBST(nums[half+1:])
Insert a line here.

2024-07-13 23:23 UTC, closed without merging