add 110 Balanced Binary Tree
kobakobashu/leetcode pull request #48
Opened 2021-04-28 01:45 UTC by kobakobashu

time : 35m

2021-04-28 01:45 UTC, kobakobashu commented
Please check my code.

2021-04-29 14:58 UTC, ryuji0123 requested changes

2021-04-29 14:58 UTC, ryuji0123 commented on 110.balanced-binary-tree.py
> +    def depth(self, node):
insert a line before defining function

2021-04-29 14:58 UTC, ryuji0123 commented on 110.balanced-binary-tree.py
> +        node_left = self.depth(root.left)
node_left is a very weird name because it is actually depth

2021-05-01 15:51 UTC, kobakobashu commented
I fixed my code.  Please check it.

2024-06-12 23:19 UTC, closed without merging