add 111 minimum-depth-of-binary-tree
kobakobashu/leetcode pull request #50
Opened 2021-04-28 14:18 UTC by kobakobashu

time : 30m

2021-04-28 14:18 UTC, kobakobashu commented
Please check my code.

2021-04-29 14:53 UTC, ryuji0123 requested changes

2021-04-29 14:53 UTC, ryuji0123 commented on 111.minimum-depth-of-binary-tree.py
> +        else:
unnecessary else statement

2021-05-01 15:57 UTC, kobakobashu commented
I fixed my code.  Please check it.

2021-05-02 11:32 UTC, ryuji0123 approved these changes

2021-05-04 01:58 UTC, merged