add 112 path-sum
kobakobashu/leetcode pull request #52
Opened 2021-04-30 02:50 UTC by kobakobashu

time : 25m

2021-04-30 02:50 UTC, kobakobashu commented
Please check my code.

2021-05-01 11:32 UTC, ryuji0123 requested changes

2021-05-01 11:32 UTC, ryuji0123 commented on 112.path-sum.py
> +        if not root.left and not root.right and root.val == targetSum:
```py
if not root.left and not root.right:
    return root.val == targetSum
```

2021-05-01 16:15 UTC, kobakobashu commented
rebase 忘れた結果，勝手に close してしまいました．直します．

2021-05-01 16:23 UTC, kobakobashu commented
I fixed my code.  Please check it.

2021-05-02 11:28 UTC, ryuji0123 requested changes

2021-05-02 11:28 UTC, ryuji0123 commented on 112.path-sum.py
> +            return root.val== targetSum
You don't seem to use flake8 or other linter. I told you to use one.

2021-05-04 02:23 UTC, kobakobashu commented
I used flake8, and fixed my code.  Please check it.

2021-05-04 13:28 UTC, ryuji0123 approved these changes

2021-05-05 14:45 UTC, merged