add 118 pascals-angle
kobakobashu/leetcode pull request #54
Opened 2021-04-30 03:35 UTC by kobakobashu

time : 15m

2021-04-30 03:35 UTC, kobakobashu commented
Please check my code.

2021-05-01 11:30 UTC, ryuji0123 requested changes

2021-05-01 11:30 UTC, ryuji0123 commented on 118.pascals-triangle.py
> +            for cul_num in range(1, Row - 1):
Do you mean col_num?

2021-05-01 16:21 UTC, kobakobashu commented on 118.pascals-triangle.py
> +            for cul_num in range(1, Row - 1):
パスカルの三角形を行列と捉え，row に対応するものを考えて，column の col としました．

2021-05-02 11:36 UTC, ryuji0123 commented on 118.pascals-triangle.py
> +            for cul_num in range(1, Row - 1):
What cul_num?

2021-05-02 11:37 UTC, ryuji0123 commented on 118.pascals-triangle.py
> +            for cul_num in range(1, Row - 1):
If it's a mistake, modify other PR.

2024-07-13 23:24 UTC, closed without merging