add 121 best-time-to-buy-and-sell-stock
kobakobashu/leetcode pull request #58
Opened 2021-05-01 17:17 UTC by kobakobashu

time : 5m

2021-05-01 17:18 UTC, kobakobashu commented
Please check my code.

2021-05-02 11:25 UTC, ryuji0123 requested changes

2021-05-02 11:25 UTC, ryuji0123 commented on 121.best-time-to-buy-and-sell-stock.py
> +        profit = 0
profit is better than unclear variables such as output. But it's not perfect. Use max_profit.
Also, this function's name is bad. The best name is compute_max_profit. It's a good time to see "Readable code", then you'll understand what I mean.

2021-05-04 02:40 UTC, kobakobashu commented
I changed the variable name.  Please check my code.

2021-05-04 13:28 UTC, ryuji0123 approved these changes

2021-05-05 14:46 UTC, merged