add 122 best-time-to-buy-and-sell-stock-ii
kobakobashu/leetcode pull request #60
Opened 2021-05-03 15:02 UTC by kobakobashu

time : 10m

2021-05-03 15:03 UTC, kobakobashu commented
Please check my code.

2021-05-04 13:27 UTC, ryuji0123 requested changes

2021-05-04 13:27 UTC, ryuji0123 commented on 122.best-time-to-buy-and-sell-stock-ii.py
> +            if pre_price <= prices[day]:
define cur_price first

2021-05-06 05:30 UTC, kobakobashu commented
I defined cur_price first and made a few changes to the code.  Please check it.

2024-06-12 23:19 UTC, closed without merging