add 125 valid-palindrome
kobakobashu/leetcode pull request #62
Opened 2021-05-04 03:25 UTC by kobakobashu

time : 15m

2021-05-04 03:25 UTC, kobakobashu commented
Please check my code.

2021-05-04 13:21 UTC, ryuji0123 requested changes

2021-05-04 13:21 UTC, ryuji0123 commented on 125.valid-palindrome.py
> +        for word in s.lower():
word -> character or char

2021-05-04 13:21 UTC, ryuji0123 commented on 125.valid-palindrome.py
> +        only_alphabet_num_list = []
use filter function to define only_alphabet_num_list

2021-05-06 05:58 UTC, kobakobashu commented
I changed variable name and used filter function.  Please check my code.

2024-06-12 23:19 UTC, closed without merging