add 136 single-number
kobakobashu/leetcode pull request #64
Opened 2021-05-06 04:31 UTC by kobakobashu

time : 10m

2021-05-06 04:34 UTC, kobakobashu commented
I'm sorry for the late submission.  Could you check my code ?

2021-05-06 13:28 UTC, ryuji0123 requested changes

2021-05-06 13:28 UTC, ryuji0123 commented on 136.single-number.py
> +        for num in range(0, len(nums) - 1, 2):
num is weird here because it's used like this:

```py
for num in nums:
```

2021-05-08 11:00 UTC, kobakobashu commented on 136.single-number.py
> +        for num in range(0, len(nums) - 1, 2):
num が数字自体を意味するため、◯番目という変数名に num を使うというのはおかしいということですね。
この場合どのような変数名が適切なのでしょうか。調べてみても、i や num ばかりで参考になりませんでした。。

2024-07-13 23:23 UTC, closed without merging