add 13 roman-to-integer
kobakobashu/leetcode pull request #8
Opened 2021-04-07 02:28 UTC by kobakobashu

15m

2021-04-07 02:34 UTC, kobakobashu commented
Please check my code.

2021-04-07 02:44 UTC, ryuji0123 requested changes
Don't commit  `9.palindrome-number.py`

2021-04-07 02:44 UTC, ryuji0123 commented on 13.roman-to-integer.py
> +#
write time & space complexity

2021-04-08 09:15 UTC, kobakobashu commented
rebaseかけるタイミングを間違えて、全てcommitしてしまいました。コミットしたファイルを取り消す方法を調べている中です。間違えが重なってしまい、申し訳ございません。

2021-04-08 10:16 UTC, ryuji0123 commented
今回の場合、9.palindrome-number.py の PR を main に merge した後で rebase をかければ commit から外れると思うのですが、現状どうですか？

2021-04-08 11:03 UTC, kobakobashu commented
うまくいきました！ありがとうございます！よろしければレビューお願いします。

2021-04-09 04:16 UTC, ryuji0123 requested changes

2021-04-09 04:16 UTC, ryuji0123 commented on 13.roman-to-integer.py
> +        dict_ = {'I' : 1, 'V' : 5, 'X' : 10, 'L' : 50, 'C' : 100, 'D' : 500, 'M' : 1000,}
dict_ is better than dict, but it just shows the type of the variable. Change the name to xxx_dict, xxx_hash, xxx_map.
One simple name is roman_dict

2021-04-09 04:42 UTC, ryuji0123 approved these changes
LGTM

2021-04-09 04:43 UTC, kobakobashu commented
Thanks for checking my code

2021-04-09 04:44 UTC, merged